### PR TITLE
Create Server.js

### PR DESCRIPTION
**Pull request by RandomAltThing**

### CODE REVIEW

**Comment by Falkirks** [comment]
Thanks, but that file won't do anything except echo out messages.

**Comment by Falkirks** [comment]
https://github.com/Falkirks/DirtServer/blob/master/main.js is where the server is started.

**Comment by RandomAltThing** [comment]
1. How come main.js doesn't display when you click on  */src*?
2. Is this project even possible? If so, will you continue it?

**Comment by Falkirks** [comment]
`main.js` is like `start.sh` and is outside the `src` folder. This project is possible an I have made important progress on it, however I don't think it will be continued as it is hard to maintain.

**Pull request closed without merging**
